services:
    gateway:
        image: nginx
        ports: ["8080:80"]
        volumes: 
            - ./src/Gateway/nginx.conf:/etc/nginx/nginx.conf
            - ./src/Web.Home/build:/var/www/html


    identity-server:
        build: src/IdentityServer/
        environment:
            ASPNETCORE_ENVIRONMENT: Docker  

    weather-service:
        build: src/Service.Core.Weather/
        environment:
            ASPNETCORE_ENVIRONMENT: Docker  
