
POST http://localhost:5000/connect/authorize
Content-Type: application/x-www-form-urlencoded

client_id=client
&scope=weather.read
&response_type=token
&redirect_uri=http://localhost:3000/account
&state=abc
&nonce=xyz
