
# @name login
POST http://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=customer&grant_type=password&username=jsoliveira&password=1234&scope=openid profile

###

POST http://localhost:5001/connect/userinfo
Authorization: Bearer {{login.response.body.$.access_token}}